### ISSUE TITLE
Unable to resolve reference CompilerServices.Unsafe

### ISSUE THREAD

**Issue by peyman1959** [hadashiA/VitalRouter#72]
Hi
when I install the nuget packages, I get this error
Unity 2022.3.18
`Assembly 'Assets/Packages/VitalRouter.1.2.0/lib/netstandard2.1/VitalRouter.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Runtime.CompilerServices.Unsafe'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.`
after disabling validation error goes, but I wonder does it spouse to be this way?
then I add unity package with git url and got 19 errors
`Plugin 'Assets/Packages/VitalRouter.1.2.0/lib/netstandard2.1/VitalRouter.dll' has the same filename as Assembly Definition File 'Packages/jp.hadashikick.vitalrouter/Runtime/VitalRouter.asmdef'. Rename the assemblies to avoid hard to diagnose issues and crashes.`
`Library\PackageCache\jp.hadashikick.vitalrouter@7111aa8fa6\Runtime\Internal\FreeList.cs(177,28): error CS0122: 'Unsafe' is inaccessible due to its protection level`
`Library\PackageCache\jp.hadashikick.vitalrouter@7111aa8fa6\Runtime\Internal\FreeList.cs(178,26): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('TTo')
`

**Comment by hadashiA** [comment]
@peyman1959 Hi, thanks for the report.
This is my mistake.
I've released a fix in 1.2.1 for you to try.
https://github.com/hadashiA/VitalRouter/releases/tag/1.2.1

**Comment by peyman1959** [comment]
thanks but it didnt fixed.
with nuget packages issue still remaining
but with unity package errors are down to 6 
`Library\PackageCache\jp.hadashikick.vitalrouter@e24ee5317b\Runtime\AnonymousSubscriber.cs(80,33): error CS0122: 'Unsafe' is inaccessible due to its protection level`
`Library\PackageCache\jp.hadashikick.vitalrouter@e24ee5317b\Runtime\AnonymousSubscriber.cs(81,22): error CS1503: Argument 1: cannot convert from 'TTo' to 'T'
`
`Library\PackageCache\jp.hadashikick.vitalrouter@e24ee5317b\Runtime\AnonymousSubscriber.cs(57,25): error CS0122: 'Unsafe' is inaccessible due to its protection level`
`Library\PackageCache\jp.hadashikick.vitalrouter@e24ee5317b\Runtime\AnonymousSubscriber.cs(58,70): error CS1503: Argument 3: cannot convert from 'T' to 'VitalRouter.PublishContinuation<TReceive>'`
`Library\PackageCache\jp.hadashikick.vitalrouter@e24ee5317b\Runtime\AnonymousSubscriber.cs(60,33): error CS0122: 'Unsafe' is inaccessible due to its protection level
`
`Library\PackageCache\jp.hadashikick.vitalrouter@e24ee5317b\Runtime\AnonymousSubscriber.cs(61,29): error CS1503: Argument 1: cannot convert from 'TTo' to 'T'
`

**Comment by hadashiA** [comment]
That. Sorry.
More fixes, try [v1.2.2](https://github.com/hadashiA/VitalRouter/releases/tag/1.2.2).
Thanks again for the repeated reports ><

**Comment by peyman1959** [comment]
Thank you .
It fixed
